name: workmanager_android
description: Android implementation of the workmanager plugin.
version: 0.9.0+2
publish_to: none
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  workmanager_platform_interface: 
    git: https://github.com/kumsumit/workmanager_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: workmanager
    platforms:
      android:
        package: dev.fluttercommunity.workmanager
        pluginClass: WorkmanagerPlugin